description: sub_intf_scale
heat_template_version: 'rocky'

resources:
  My_IPAM:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: my-scale-ipam
  

  Sub_VN-5:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 47.27.0.80,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 28,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-5:
    depends_on: [Sub_VN-5]
    properties:
      name: sub-interface-5
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 6}
      virtual_machine_interface_refs: [958de51d-5fa9-480a-92da-28fced1a2d59]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-5, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-5 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-5, Sub_VN-5 ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-5 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-5 , fq_name ] } ] }]
      instance_ip_address: 47.27.0.83

  BGP_TAGGED-5:
    depends_on: [SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 47.27.0.83
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-5
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-5}
    type: OS::ContrailV2::BgpAsAService

  Sub_VN-6:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 47.27.0.96,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 28,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-6:
    depends_on: [Sub_VN-6]
    properties:
      name: sub-interface-6
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 7}
      virtual_machine_interface_refs: [958de51d-5fa9-480a-92da-28fced1a2d59]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-6, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-6 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-6, Sub_VN-6 ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-6 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-6 , fq_name ] } ] }]
      instance_ip_address: 47.27.0.99

  BGP_TAGGED-6:
    depends_on: [SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 47.27.0.99
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-6
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-6}
    type: OS::ContrailV2::BgpAsAService

  Sub_VN-7:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 47.27.0.112,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 28,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-7:
    depends_on: [Sub_VN-7]
    properties:
      name: sub-interface-7
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 8}
      virtual_machine_interface_refs: [958de51d-5fa9-480a-92da-28fced1a2d59]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-7, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-7 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-7, Sub_VN-7 ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-7 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-7 , fq_name ] } ] }]
      instance_ip_address: 47.27.0.115

  BGP_TAGGED-7:
    depends_on: [SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 47.27.0.115
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-7
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-7}
    type: OS::ContrailV2::BgpAsAService

  Sub_VN-8:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 47.27.0.128,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 28,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-8:
    depends_on: [Sub_VN-8]
    properties:
      name: sub-interface-8
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 9}
      virtual_machine_interface_refs: [958de51d-5fa9-480a-92da-28fced1a2d59]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-8, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-8 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-8, Sub_VN-8 ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-8 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-8 , fq_name ] } ] }]
      instance_ip_address: 47.27.0.131

  BGP_TAGGED-8:
    depends_on: [SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 47.27.0.131
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-8
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-8}
    type: OS::ContrailV2::BgpAsAService

  Sub_VN-9:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 47.27.0.144,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 28,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-9:
    depends_on: [Sub_VN-9]
    properties:
      name: sub-interface-9
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 10}
      virtual_machine_interface_refs: [958de51d-5fa9-480a-92da-28fced1a2d59]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-9, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-9 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-9, Sub_VN-9 ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-9 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-9 , fq_name ] } ] }]
      instance_ip_address: 47.27.0.147

  BGP_TAGGED-9:
    depends_on: [SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 47.27.0.147
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-9
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-9}
    type: OS::ContrailV2::BgpAsAService

