description: sub_intf_scale
heat_template_version: 'rocky'

resources:
  My_IPAM:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: my-scale-ipam
  

  Sub_VN-0:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 27.27.0.0,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 28,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-0:
    depends_on: [Sub_VN-0]
    properties:
      name: sub-interface-0
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 1}
      virtual_machine_interface_refs: [5ecde63d-7f52-4db2-b198-08aebd829c1c]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-0, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-0 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-0, Sub_VN-0 ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-0 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-0 , fq_name ] } ] }]
      instance_ip_address: 27.27.0.3

  BGP_TAGGED-0:
    depends_on: [SubInterface-0, SubInterface-1, SubInterface-2, SubInterface-3, SubInterface-4, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.3
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-0
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-0}
    type: OS::ContrailV2::BgpAsAService

  Sub_VN-1:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 27.27.0.16,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 28,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-1:
    depends_on: [Sub_VN-1]
    properties:
      name: sub-interface-1
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 2}
      virtual_machine_interface_refs: [5ecde63d-7f52-4db2-b198-08aebd829c1c]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-1, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-1 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-1, Sub_VN-1 ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-1 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-1 , fq_name ] } ] }]
      instance_ip_address: 27.27.0.19

  BGP_TAGGED-1:
    depends_on: [SubInterface-0, SubInterface-1, SubInterface-2, SubInterface-3, SubInterface-4, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.19
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-1
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-1}
    type: OS::ContrailV2::BgpAsAService

  Sub_VN-2:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 27.27.0.32,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 28,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-2:
    depends_on: [Sub_VN-2]
    properties:
      name: sub-interface-2
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 3}
      virtual_machine_interface_refs: [5ecde63d-7f52-4db2-b198-08aebd829c1c]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-2, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-2 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-2, Sub_VN-2 ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-2 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-2 , fq_name ] } ] }]
      instance_ip_address: 27.27.0.35

  BGP_TAGGED-2:
    depends_on: [SubInterface-0, SubInterface-1, SubInterface-2, SubInterface-3, SubInterface-4, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.35
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-2
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-2}
    type: OS::ContrailV2::BgpAsAService

  Sub_VN-3:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 27.27.0.48,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 28,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-3:
    depends_on: [Sub_VN-3]
    properties:
      name: sub-interface-3
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 4}
      virtual_machine_interface_refs: [5ecde63d-7f52-4db2-b198-08aebd829c1c]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-3, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-3 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-3, Sub_VN-3 ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-3 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-3 , fq_name ] } ] }]
      instance_ip_address: 27.27.0.51

  BGP_TAGGED-3:
    depends_on: [SubInterface-0, SubInterface-1, SubInterface-2, SubInterface-3, SubInterface-4, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.51
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-3
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-3}
    type: OS::ContrailV2::BgpAsAService

  Sub_VN-4:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 27.27.0.64,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 28,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-4:
    depends_on: [Sub_VN-4]
    properties:
      name: sub-interface-4
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 5}
      virtual_machine_interface_refs: [5ecde63d-7f52-4db2-b198-08aebd829c1c]
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-4, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-4 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-4, Sub_VN-4 ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-4 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-4 , fq_name ] } ] }]
      instance_ip_address: 27.27.0.67

  BGP_TAGGED-4:
    depends_on: [SubInterface-0, SubInterface-1, SubInterface-2, SubInterface-3, SubInterface-4, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.67
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-4
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-4}
    type: OS::ContrailV2::BgpAsAService

