description: vSRX-Scale
heat_template_version: 'rocky'

outputs:
  vsrx_id:
    description: vsrx handle
    value:
      get_attr: [VSRX-scale, show, id]

resources:
  My_IPAM:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: my-scale-ipam

  My_VN:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 27.37.47.0,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 29,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork
  
  ParentPort:
    depends_on: [My_VN]
    properties:
      name: parent-port-1
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_parent_IP :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ ParentPort, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : ParentPort }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]


  Sub_VN-1:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 7.17.0.0,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 18,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-1:
    depends_on: [Sub_VN-1]
    properties:
      name: sub-interface-1
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 2}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-1, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-1 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-1, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-1 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-1 , fq_name ] } ] }]
      instance_ip_address: 7.17.0.3

  Sub_VN-2:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 7.17.64.0,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 18,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-2:
    depends_on: [Sub_VN-2]
    properties:
      name: sub-interface-2
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 3}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-2, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-2 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-2, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-2 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-2 , fq_name ] } ] }]
      instance_ip_address: 7.17.64.3

  Sub_VN-3:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 7.17.128.0,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 18,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-3:
    depends_on: [Sub_VN-3]
    properties:
      name: sub-interface-3
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 4}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-3, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-3 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-3, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-3 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-3 , fq_name ] } ] }]
      instance_ip_address: 7.17.128.3

  Sub_VN-4:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 7.17.192.0,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 18,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork

  SubInterface-4:
    depends_on: [Sub_VN-4]
    properties:
      name: sub-interface-4
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 5}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ Sub_VN-4, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-4 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-4, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-4 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ Sub_VN-4 , fq_name ] } ] }]
      instance_ip_address: 7.17.192.3


  VSRX-scale:
    depends_on: [My_VN, ParentPort, SubInterface-1, SubInterface-2, SubInterface-3, SubInterface-4, ]
    properties:
      config_drive: 'true'
      user_data_format: RAW
      # personality: { /config/junos-config/configuration.txt: { get_file: /contrail-test/serial_scripts/solution/topology/mini_deployment/vsrx_config/bgpaas_config.txt } }
      flavor: contrail_flavor_2cpu
      image: vsrx
      name: VSRX-scale
      networks:
      - port: {get_resource: ParentPort}
    type: OS::Nova::Server


  BGP_TAGGED-1:
    depends_on: [SubInterface-1, SubInterface-2, SubInterface-3, SubInterface-4, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 7.17.0.3
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-1
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-1}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-2:
    depends_on: [SubInterface-1, SubInterface-2, SubInterface-3, SubInterface-4, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 7.17.64.3
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-2
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-2}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-3:
    depends_on: [SubInterface-1, SubInterface-2, SubInterface-3, SubInterface-4, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 7.17.128.3
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-3
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-3}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-4:
    depends_on: [SubInterface-1, SubInterface-2, SubInterface-3, SubInterface-4, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 7.17.192.3
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-4
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-4}
    type: OS::ContrailV2::BgpAsAService
