description: vSRX-Scale
heat_template_version: 'rocky'

resources:
  My_IPAM:
    type: OS::ContrailV2::NetworkIpam
    properties:
      name: my-scale-ipam

  My_VN:
    depends_on: [My_IPAM]
    properties:
      name: sub-scale-vn
      network_ipam_refs: [{ get_resource: My_IPAM }]
      network_ipam_refs_data:
        [{
          network_ipam_refs_data_ipam_subnets:
            [{
              network_ipam_refs_data_ipam_subnets_subnet:
                {
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix: 27.27.0.0,
                  network_ipam_refs_data_ipam_subnets_subnet_ip_prefix_len: 28,
                },
                network_ipam_refs_data_ipam_subnets_addr_from_start: 'true',
         }]
         },
        ]
    type: OS::ContrailV2::VirtualNetwork
  
  ParentPort:
    depends_on: [My_VN]
    properties:
      name: parent-port-1
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_parent_IP :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ ParentPort, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : ParentPort }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]


  SubInterface-2:
    depends_on: [My_VN]
    properties:
      name: sub-interface-2
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 2}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-2 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-2, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-2 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]
      instance_ip_address: 27.27.0.4

  SubInterface-3:
    depends_on: [My_VN]
    properties:
      name: sub-interface-3
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 3}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-3 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-3, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-3 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]
      instance_ip_address: 27.27.0.5

  SubInterface-4:
    depends_on: [My_VN]
    properties:
      name: sub-interface-4
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 4}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-4 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-4, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-4 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]
      instance_ip_address: 27.27.0.6

  SubInterface-5:
    depends_on: [My_VN]
    properties:
      name: sub-interface-5
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 5}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-5 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-5, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-5 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]
      instance_ip_address: 27.27.0.7

  SubInterface-6:
    depends_on: [My_VN]
    properties:
      name: sub-interface-6
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 6}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-6 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-6, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-6 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]
      instance_ip_address: 27.27.0.8

  SubInterface-7:
    depends_on: [My_VN]
    properties:
      name: sub-interface-7
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 7}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-7 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-7, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-7 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]
      instance_ip_address: 27.27.0.9

  SubInterface-8:
    depends_on: [My_VN]
    properties:
      name: sub-interface-8
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 8}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-8 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-8, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-8 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]
      instance_ip_address: 27.27.0.10

  SubInterface-9:
    depends_on: [My_VN]
    properties:
      name: sub-interface-9
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 9}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-9 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-9, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-9 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]
      instance_ip_address: 27.27.0.11

  SubInterface-10:
    depends_on: [My_VN]
    properties:
      name: sub-interface-10
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 10}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-10 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-10, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-10 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]
      instance_ip_address: 27.27.0.12

  SubInterface-11:
    depends_on: [My_VN]
    properties:
      name: sub-interface-11
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 11}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-11 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-11, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-11 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]
      instance_ip_address: 27.27.0.13

  SubInterface-12:
    depends_on: [My_VN]
    properties:
      name: sub-interface-12
      virtual_machine_interface_properties: {virtual_machine_interface_properties_sub_interface_vlan_tag: 12}
      virtual_machine_interface_refs:
      - {get_resource: ParentPort}
      virtual_network_refs: [{ list_join: [':', { get_attr: [ My_VN, fq_name ] } ] }]
    type: OS::ContrailV2::VirtualMachineInterface

  VMI_sub_IP-12 :
    type: OS::ContrailV2::InstanceIp
    depends_on : [ SubInterface-12, My_VN ]
    properties :
      virtual_machine_interface_refs : [{ get_resource : SubInterface-12 }]
      virtual_network_refs : [{ list_join : [':', { get_attr : [ My_VN , fq_name ] } ] }]
      instance_ip_address: 27.27.0.14


  VSRX-Nuthan:
    depends_on: [My_VN, ParentPort, SubInterface-2, SubInterface-3, SubInterface-4, SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, SubInterface-10, SubInterface-11, SubInterface-12, ]
    properties:
      config_drive: 'true'
      user_data_format: RAW
      # personality: { /config/junos-config/configuration.txt: { get_file: /contrail-test/serial_scripts/solution/topology/mini_deployment/vsrx_config/bgpaas_config.txt } }
      flavor: contrail_flavor_2cpu
      image: vsrx
      name: VSRX-Nuthan
      networks:
      - port: {get_resource: ParentPort}
    type: OS::Nova::Server


  BGP_TAGGED-2:
    depends_on: [SubInterface-2, SubInterface-3, SubInterface-4, SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, SubInterface-10, SubInterface-11, SubInterface-12, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.4
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-2
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-2}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-3:
    depends_on: [SubInterface-2, SubInterface-3, SubInterface-4, SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, SubInterface-10, SubInterface-11, SubInterface-12, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.5
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-3
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-3}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-4:
    depends_on: [SubInterface-2, SubInterface-3, SubInterface-4, SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, SubInterface-10, SubInterface-11, SubInterface-12, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.6
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-4
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-4}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-5:
    depends_on: [SubInterface-2, SubInterface-3, SubInterface-4, SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, SubInterface-10, SubInterface-11, SubInterface-12, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.7
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-5
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-5}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-6:
    depends_on: [SubInterface-2, SubInterface-3, SubInterface-4, SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, SubInterface-10, SubInterface-11, SubInterface-12, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.8
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-6
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-6}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-7:
    depends_on: [SubInterface-2, SubInterface-3, SubInterface-4, SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, SubInterface-10, SubInterface-11, SubInterface-12, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.9
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-7
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-7}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-8:
    depends_on: [SubInterface-2, SubInterface-3, SubInterface-4, SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, SubInterface-10, SubInterface-11, SubInterface-12, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.10
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-8
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-8}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-9:
    depends_on: [SubInterface-2, SubInterface-3, SubInterface-4, SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, SubInterface-10, SubInterface-11, SubInterface-12, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.11
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-9
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-9}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-10:
    depends_on: [SubInterface-2, SubInterface-3, SubInterface-4, SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, SubInterface-10, SubInterface-11, SubInterface-12, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.12
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-10
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-10}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-11:
    depends_on: [SubInterface-2, SubInterface-3, SubInterface-4, SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, SubInterface-10, SubInterface-11, SubInterface-12, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.13
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-11
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-11}
    type: OS::ContrailV2::BgpAsAService

  BGP_TAGGED-12:
    depends_on: [SubInterface-2, SubInterface-3, SubInterface-4, SubInterface-5, SubInterface-6, SubInterface-7, SubInterface-8, SubInterface-9, SubInterface-10, SubInterface-11, SubInterface-12, ]
    properties:
      autonomous_system: 64500
      bgpaas_ip_address: 27.27.0.14
      bgpaas_session_attributes:
        bgpaas_session_attributes_address_families:
          bgpaas_session_attributes_address_families_family: [inet]
        bgpaas_session_attributes_as_override: true
      name: BGPAAS-12
      virtual_machine_interface_refs:
      - {get_resource: SubInterface-12}
    type: OS::ContrailV2::BgpAsAService
