apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-auth-policy
  namespace: kube-system
  labels:
    k8s-app: k8s-keystone-auth
data:
  policies:
  - resource:
      verbs:
      - get
      resources:
      - Pod
      version:
      - '*'
      namespace:
      - '*'
    match:
    - type: role
      values:
      - '*'
    - type: project
      values:
      - admin
