
apiVersion: v1
kind: ConfigMap
metadata:
  name: k8s-auth-policy
  namespace: kube-system
  labels:
    k8s-app: k8s-keystone-auth
data:
  policies: |
    [
      {
        "resource": {
          "verbs": [
            "*"
          ],
          "resources": [
            "*"
          ],
          "version": "*",
          "namespace": "*"
        },
        "match": [
          {
            "type": "role",
            "values": [
              "*"
            ]
          },
          {
            "type": "project",
            "values": [
              "admin"
            ]
          }
        ]
      },
      {
        "resource": {
          "resources": [
            "*"
          ],
          "verbs": [
            "*"
          ],
          "version": "*",
          "namespace": "*"
        },
        "match": [
          {
            "type": "role",
            "values": [
              "Member"
            ]
          },
          {
            "type": "project",
            "values": [
              "test_project"
            ]
          },
          {
            "type": "user",
            "values": [
              "test"
            ]
          }
        ]
      },
      {
        "resource": {
          "resources": [
            "pods", "deployments"
          ],
          "verbs": [
            "create"
          ],
          "version": "*",
          "namespace": "*"
        },
        "match": [
          {
            "type": "role",
            "values": [
              "Member"
            ]
          },
          {
            "type": "project",
            "values": [
              "ola_project"
            ]
          },
          {
            "type": "user",
            "values": [
              "ola"
            ]
          }
        ]
      },
      {
        "resource": {
          "resources": [
            "pods", "deployments"
          ],
          "verbs": [
            "delete"
          ],
          "version": "*",
          "namespace": "*"
        },
        "match": [
          {
            "type": "role",
            "values": [
              "Member"
            ]
          },
          {
            "type": "project",
            "values": [
              "uber_project"
            ]
          },
          {
            "type": "user",
            "values": [
              "uber"
            ]
          }
        ]
      },
      {
        "resource": {
          "resources": [
            "services"
          ],
          "verbs": [
            "*"
          ],
          "version": "*",
          "namespace": "zomsrc"
        },
        "match": [
          {
            "type": "role",
            "values": [
              "Member"
            ]
          },
          {
            "type": "project",
            "values": [
              "zomato_project"
            ]
          },
          {
            "type": "user",
            "values": [
              "zomato"
            ]
          }
        ]
      },
      {
        "resource": {
          "resources": [
            "pods", "deployments", "services"
          ],
          "verbs": [
            "*"
          ],
          "version": "*",
          "namespace": "easy"
        },
        "match": [
          {
            "type": "role",
            "values": [
              "Member"
            ]
          },
          {
            "type": "project",
            "values": [
              "zoro_project"
            ]
          },
          {
            "type": "user",
            "values": [
              "zoro"
            ]
          }
        ]
      }
    ]
